/**:
  ros__parameters:
    # motion state constraints
    max_velocity: 20.0
    stop_decel: 0.0

    # external velocity limit parameter
    margin_to_insert_external_velocity_limit: 0.3

    # -- curve parameters --
    curvature_calculation_distance: 3.0 #2.5         # 수정: 2.0 -> 2.5 (곡률 계산 안정성)
    enable_lateral_acc_limit: true
    max_lateral_accel: 4.7 #4.5 #5.0                     # 수정: 3.5 -> 3.0 (S자 코너 안정성)
    min_curve_velocity: 3.7 #3.5 #4.5                    # 수정: 3.5 -> 3.0 (코너 내 속도 유지)
    decel_distance_before_curve: 5.0 #0.5           # 수정: 1.0 -> 0.5 (S자 코너 감속 완화)
    decel_distance_after_curve: 0.0
    min_decel_for_lateral_acc_lim_filter: -2.0 # 수정: -2.5 -> -2.0 (감속 유연화)
    enable_steering_rate_limit: true
    max_steering_angle_rate: 40.0              # 수정: 40.0 -> 50.0 (조향 반응성 강화)
    resample_ds: 0.15                          # 수정: 0.1 -> 0.15 (샘플링 부드러움)
    curvature_threshold: 0.03                  # 수정: 0.02 -> 0.03 (조향 제한 완화)

    # engage & replan parameters
    replan_vel_deviation: 5.53
    engage_velocity: 4.0 #3.5                       # 수정: 5.0 -> 4.0 (코너 진입 속도 조정)
    engage_acceleration: 0.4 #0.3                   # 수정: 0.3 -> 0.4 (속도 회복 개선)
    engage_exit_ratio: 0.1
    stop_dist_to_prohibit_engage: 0.5

    # stop velocity
    stopping_velocity: 4.0 #2.778
    stopping_distance: 0.0

    # path extraction parameters
    extract_ahead_dist: 200.0
    extract_behind_dist: 5.0
    delta_yaw_threshold: 1.0472

    # resampling parameters for optimization
    max_trajectory_length: 200.0
    min_trajectory_length: 180.0
    resample_time: 2.0
    dense_resample_dt: 0.1                     # 수정: 0.2 -> 0.1 (빠른 경로 업데이트)
    dense_min_interval_distance: 0.15          # 수정: 0.1 -> 0.15 (샘플링 간격 조정)
    sparse_resample_dt: 0.5
    sparse_min_interval_distance: 4.0

    # resampling parameters for post process
    post_max_trajectory_length: 300.0
    post_min_trajectory_length: 30.0
    post_resample_time: 10.0
    post_dense_resample_dt: 0.1
    post_dense_min_interval_distance: 0.1
    post_sparse_resample_dt: 0.1
    post_sparse_min_interval_distance: 1.0

    # system
    over_stop_velocity_warn_thr: 1.389
    plan_from_ego_speed_on_manual_mode: false