/**:
  ros__parameters:
    # -- system --
    traj_resample_dist: 0.1
    use_steer_prediction: false
    admissible_position_error: 3.0
    admissible_yaw_error_rad: 1.0

    # -- path smoothing --
    enable_path_smoothing: false
    path_filter_moving_ave_num: 8
    curvature_smoothing_num_traj: 8
    curvature_smoothing_num_ref_steer: 8

    # -- trajectory extending --
    extend_trajectory_for_end_yaw_control: true

    # -- mpc optimization --
    qp_solver_type: "osqp"
    mpc_prediction_horizon: 15
    mpc_prediction_dt: 0.005
    mpc_weight_lat_error: 2.5
    mpc_weight_heading_error: 0.5
    mpc_weight_heading_error_squared_vel: 0.4
    mpc_weight_steering_input: 0.8
    mpc_weight_steering_input_squared_vel: 0.15
    mpc_weight_lat_jerk: 0.3
    mpc_weight_steer_rate: 0.03
    mpc_weight_steer_acc: 0.0005
    mpc_low_curvature_weight_lat_error: 3.0
    mpc_low_curvature_weight_heading_error: 0.6
    mpc_low_curvature_weight_heading_error_squared_vel: 0.4
    mpc_low_curvature_weight_steering_input: 0.8
    mpc_low_curvature_weight_steering_input_squared_vel: 0.15
    mpc_low_curvature_weight_lat_jerk: 0.0
    mpc_low_curvature_weight_steer_rate: 0.03
    mpc_low_curvature_weight_steer_acc: 0.0005
    mpc_low_curvature_thresh_curvature: 0.03
    mpc_weight_terminal_lat_error: 1.5
    mpc_weight_terminal_heading_error: 0.2
    mpc_zero_ff_steer_deg: 0.3
    mpc_acceleration_limit: 3.0
    mpc_velocity_time_constant: 0.2
    mpc_min_prediction_length: 10.0

    # -- vehicle model --
    vehicle_model_type: "kinematics"
    input_delay: 0.1
    vehicle_model_steer_tau: 0.15
    steer_rate_lim_dps_list_by_curvature: [80.0, 90.0, 100.0]
    curvature_list_for_steer_rate_lim: [0.001, 0.002, 0.01]
    steer_rate_lim_dps_list_by_velocity: [100.0, 90.0, 80.0]
    velocity_list_for_steer_rate_lim: [10.0, 15.0, 20.0]
    acceleration_limit: 3.0
    velocity_time_constant: 0.2

    # -- lowpass filter for noise reduction --
    steering_lpf_cutoff_hz: 3.0
    error_deriv_lpf_cutoff_hz: 5.0

    # stop state
    stop_state_entry_ego_speed: 0.001
    stop_state_entry_target_speed: 0.001
    converged_steer_rad: 0.1
    keep_steer_control_until_converged: true
    new_traj_duration_time: 0.5
    new_traj_end_dist: 0.2
    mpc_converged_threshold_rps: 0.01

    # steer offset
    steering_offset:
      enable_auto_steering_offset_removal: true
      update_vel_threshold: 5.56
      update_steer_threshold: 0.035
      average_num: 500
      steering_offset_limit: 0.01